@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD)

autonumber

actor "Agent" as Agent
participant ":System" as System

activate Agent
    Agent -> System : asks to receive the list of properties to choose

    activate System

        System --> Agent : shows the list of announcements and asks to choose one

    deactivate System
    loop until the agent decides to leave
    Agent -> System :chooses a property

    activate System

        System --> Agent : shows the list of purchase orders\n associated with that property \nand asks to select one
    deactivate System


    Agent -> System : accepts an offer
        activate System
            System --> Agent : informs agent of successful acceptance of \npurchase order and that the user has been informed
            System --> Agent : asks agent if they want to continue or if they want to exit
        deactivate System
            Agent -> System : wants to continue
            activate System
                 System --> Agent : shows the list of properties\nand asks to select one
            deactivate System
    end
        System --> Agent : displays operation success
    deactivate System

@enduml