@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

-> CreateAnnouncementController
autonumber 3.1
loop n times
activate CreateAnnouncementController
CreateAnnouncementController -> Equipment : createEquipment(equipmentList(n))
activate Equipment
Equipment -> Equipment : addEquipment(equipment)
end
Equipment -> CreateAnnouncementController : equipmentList
deactivate Equipment

@enduml