@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false


-> CreateAnnouncementController
'hide footbox
autonumber 2.1

activate CreateAnnouncementController
CreateAnnouncementController -> Address : createAdress(street, city, district, state, zipCode)
activate Address
Address -> CreateAnnouncementController : adress


@enduml