@startuml
'skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false
skinparam linetype polyline
skinparam linetype orto

skinparam classAttributeIconSize 0

'left to right direction

class Employee {

}

class Role {
    -String id
    -String description
    --
    +Role(id, description)
    +setID
    +setDescription
    +getID
    +getDescription
}

class Address{
    -String street
    -String city
    -String district
    -String state
    -String zipCode
    --
    +Address(street, city, district, state, zipCode)
    +setStreet()
    +setCity()
    +setDistrict()
    +setState()
    +setZipCode()
    +getStreet()
    +getCity()
    +getDistrict()
    +getState()
    +getZipCode()
}

class PassportCard{
    -Integer passportNumber
    --
    +PassportCard(passportNumber)
    +getPassportNumber()
    +setPassportNumber()
}

class Person{
    -String name
    -String emailAddress
    -Integer taxNumber
    -Integer telephoneNumber
    --
    +Person(name, passportNumber, emailAdress,\ntaxNumber, contactTelephoneNumber, adress,\nrole, agency)
    +setName()
    +setEmailAddress()
    +setTaxNumber()
    +setTelephoneNumber()
    +getName()
    +getEmailAddress()
    +getTaxNumber()
    +getTelephoneNumber()
}

class Repositories {
    - Repositories()
    --
    + getInstance() : Repositories
    + getLegacyFilesRepository()
    + getOwnerRepository()
    + getAnnouncementsRepository()
}

class LegacyFileRepository {
    +addLegacyFile(filePath)
}

class OwnerRepository {
    +addOwner(name, passportNumber, taxNumber, emailAddress, contactTelephoneNumber)
}

class AnnouncementRepository {
    +addProperty(propertyType, agent, areaOfProperty, distanceFromCentre, acceptanceDate, requestDate, street, city, district, state, zipCode, photoURI, transactionType, monetaryValue)
}

class ImportLegacyFileController {
    +ImportLegacyFile(legacyFile)
}

class ImportLegacyFileUI {
    -ImportLegacyFileUI
    --
    +readFileCSV(filePath)
}

Person <|-right Employee
Person *.-- Role : role
Person *.-up Address : address
Person *.-- PassportCard : passportNumber
ImportLegacyFileUI -down.> ImportLegacyFileController
ImportLegacyFileController -down.> Repositories
Repositories -down.> LegacyFileRepository
Repositories -left.> OwnerRepository
Repositories -right.> AnnouncementRepository
Employee .> ImportLegacyFileController
@enduml